export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const FILTERED_PRODUCTS_REQUEST = "FILTERED_PRODUCTS_REQUEST";
export const FILTERED_PRODUCTS = "FILTERED_PRODUCTS";
export const FILTERED_PRODUCTS_FAIL = "FILTERED_PRODUCTS_FAIL";

export const SORT_PRODUCTS_REQUEST = "SORT_PRODUCTS_REQUEST";
export const SORT_PRODUCTS_SUCCESS = "SORT_PRODUCTS_SUCCESS";
export const SORT_PRODUCTS_FAIL = "SORT_PRODUCTS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS"